export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_START = "REGISTER_START"
export const CHECK_AUTHENTICATION = "CHECK_AUTHENTICATION";
export const USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL ="USER_LOGIN_FAIL"